# Generated by Django 3.0.5 on 2020-04-25 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=255)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('title', models.TextField(max_length=500)),
                ('text', models.TextField(max_length=5000, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subheading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subheading', models.CharField(max_length=255)),
                ('subtext', models.TextField(max_length=5000, null=True)),
                ('heading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subheadings', to='Dope_blog.Heading')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subheadings', to='Dope_blog.Posts')),
            ],
        ),
        migrations.AddField(
            model_name='heading',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='Dope_blog.Posts'),
        ),
    ]
