# Generated by Django 3.0.5 on 2020-05-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='topic',
        ),
    ]
