# Generated by Django 3.0.5 on 2020-05-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0003_auto_20200520_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='blog/images/defaultforcat.png', null=True, upload_to='blog/images/'),
        ),
    ]
