# Generated by Django 3.0.5 on 2020-04-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0003_auto_20200426_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='Dope_blog.Posts'),
        ),
    ]
