# Generated by Django 3.0.5 on 2020-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0004_auto_20200529_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='iconfinder_user-01_186382.png', null=True, upload_to=''),
        ),
    ]
