# Generated by Django 3.0.5 on 2020-04-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0004_auto_20200426_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heading',
            old_name='title',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='subheading',
            old_name='title',
            new_name='Post',
        ),
    ]
