# Generated by Django 3.0.5 on 2020-06-03 18:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0006_auto_20200603_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, null=True)),
                ('about_me', ckeditor_uploader.fields.RichTextUploadingField(max_length=500, null=True)),
                ('my_pic', models.ImageField(blank=True, default='avatar.png', null=True, upload_to='blog/aboutme/')),
            ],
        ),
    ]
