# Generated by Django 3.0.5 on 2020-04-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0007_auto_20200426_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='heading',
        ),
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.ManyToManyField(null=True, related_name='posts', to='Dope_blog.Heading'),
        ),
    ]
