# Generated by Django 3.0.5 on 2020-04-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0008_auto_20200426_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subheading',
        ),
        migrations.AddField(
            model_name='post',
            name='subheading',
            field=models.ManyToManyField(null=True, related_name='posts', to='Dope_blog.Subheading'),
        ),
    ]
