# Generated by Django 3.0.5 on 2020-04-26 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dope_blog', '0009_auto_20200426_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='head_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subheading',
            name='subhead_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subheadings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading',
            field=models.ManyToManyField(related_name='posts', to='Dope_blog.Heading'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subheading',
            field=models.ManyToManyField(related_name='posts', to='Dope_blog.Subheading'),
        ),
    ]
