# Generated by Django 3.0.5 on 2020-04-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0010_auto_20200426_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading',
            field=models.ManyToManyField(blank=True, related_name='posts', to='Dope_blog.Heading'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subheading',
            field=models.ManyToManyField(blank=True, related_name='posts', to='Dope_blog.Subheading'),
        ),
    ]
