# Generated by Django 3.0.5 on 2020-04-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0011_auto_20200426_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subheading',
        ),
        migrations.RemoveField(
            model_name='subheading',
            name='heading',
        ),
        migrations.AddField(
            model_name='heading',
            name='subheading',
            field=models.ManyToManyField(blank=True, related_name='posts', to='Dope_blog.Subheading'),
        ),
    ]
