# Generated by Django 3.0.5 on 2020-04-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0013_auto_20200426_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='subheading',
            field=models.ManyToManyField(blank=True, related_name='headings', to='Dope_blog.Subheading'),
        ),
    ]
