# Generated by Django 3.0.5 on 2020-04-26 18:18

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0015_auto_20200426_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
