# Generated by Django 3.0.5 on 2020-04-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0016_post_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='markdown',
        ),
    ]
