# Generated by Django 3.0.5 on 2020-04-27 08:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0017_remove_post_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
