# Generated by Django 3.0.5 on 2020-04-29 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0021_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Dope_blog.Comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
