# Generated by Django 3.0.5 on 2020-04-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0024_auto_20200429_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
