# Generated by Django 3.0.5 on 2020-05-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0030_auto_20200501_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='blog/images/iconfinder_user-01_186382.png', null=True, upload_to='blog/images'),
        ),
    ]
