# Generated by Django 3.0.5 on 2020-05-05 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dope_blog', '0033_auto_20200503_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, choices=[('1', 'iconfinder_user-01_186382.png'), ('2', 'full_deepmalfb.jpg')], default='blog/images/iconfinder_user-01_186382.png', null=True, upload_to='blog/images'),
        ),
    ]
