# Generated by Django 3.0.5 on 2020-05-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0034_auto_20200505_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=254)),
                ('colour', models.CharField(choices=[('1', 'primary'), ('2', 'secondary'), ('3', 'success'), ('4', 'danger'), ('5', 'warning'), ('6', 'info'), ('7', 'light'), ('8', 'dark')], default='', max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='blog/images/iconfinder_user-01_186382.png', null=True, upload_to='blog/images'),
        ),
    ]
