# Generated by Django 3.0.5 on 2020-05-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0036_auto_20200510_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='colour',
            field=models.CharField(choices=[('blue', 'primary'), ('grey', 'secondary'), ('green', 'success'), ('red', 'danger'), ('yellow', 'warning'), ('blue', 'info'), ('white', 'light'), ('black', 'dark')], max_length=254),
        ),
    ]
