# Generated by Django 3.0.5 on 2020-05-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0040_auto_20200510_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='blog/images/defaultforcat.png', null=True, upload_to='blog/images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='colour',
            field=models.CharField(choices=[('primary', 'blue'), ('secondary', 'grey'), ('success', 'green'), ('danger', 'red'), ('warning', 'yellow'), ('info', 'Sky blue'), ('light', 'white'), ('dark', 'black')], max_length=254),
        ),
        migrations.CreateModel(
            name='PostImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='blog/images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Dope_blog.Post')),
            ],
        ),
    ]
