# Generated by Django 3.0.5 on 2020-05-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dope_blog', '0041_auto_20200515_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='decs',
            field=models.CharField(default='', max_length=255),
        ),
    ]
